/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lavor.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * enum相当于Java中的enum，是枚举
 * 
 */
public enum MyEnum implements org.apache.thrift.TEnum {
  ONE(0),
  TWO(1),
  Three(2);

  private final int value;

  private MyEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MyEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return ONE;
      case 1:
        return TWO;
      case 2:
        return Three;
      default:
        return null;
    }
  }
}
